/**
 * Arabic UI strings for admin (RTL).
 */
export const ar = {
  // Nav
  dashboard: "لوحة التحكم",
  users: "المستخدمون",
  developers: "المطورون",
  properties: "العقارات",
  banks: "البنوك",
  orders: "الطلبات",
  engagement: "التفاعل",
  notifications: "الإشعارات",
  reviews: "التقييمات",
  favorites: "المفضلة",
  content: "المحتوى",
  prompts: "النماذج",
  knowledge: "المعرفة",
  system: "النظام",
  menu: "القائمة",
  navMain: "الرئيسية",
  navTeam: "فريق العمل",
  navSales: "المبيعات والطلبات",
  navData: "إدارة البيانات",
  navContent: "المحتوى والمراجعات",
  navSystem: "الإعدادات والنظام",

  // Mode Switcher
  turboMode: "تحكم سريع",
  agentMode: "وكيل AI",
  aiAgent: "وكيل الذكاء",
  switchMode: "تبديل الوضع",

  // Agent Chat
  agentWelcome: "مرحباً! أنا مساعدك الذكي. كيف يمكنني مساعدتك اليوم؟",
  agentWelcomeWithName: "مرحباً، {name}. كيف يمكنني مساعدتك؟",
  agentWelcomeDefault: "مرحباً. كيف يمكنني مساعدتك؟",
  agentPlaceholder: "اكتب رسالتك هنا...",
  agentGreetingPersonalized: "كيف أساعدك،",
  agentGreetingDefault: "كيف أقدر أساعدك اليوم؟",
  agentChipCreate: "إنشاء",
  agentChipExplore: "استكشاف",
  agentChipProperties: "عقارات",
  agentChipReview: "مراجعة",
  agentBadge: "وكيل ANAN",
  agentName: "المساعد الذكي",
  agentPendingActionsLabel: "الإجراءات المعلقة",
  agentThinking: "جاري التفكير...",
  agentSend: "إرسال",
  agentNewChat: "محادثة جديدة",
  agentSuggestions: "اقتراحات",
  createPropertySuggestion: "إنشاء عقار جديد",
  createBankSuggestion: "إضافة بنك جديد",
  createDeveloperSuggestion: "إضافة مطور جديد",
  listPropertiesSuggestion: "عرض العقارات",
  listBanksSuggestion: "عرض البنوك",
  sendFailed: "فشل إرسال الرسالة",
  createThreadFailed: "فشل إنشاء المحادثة",
  deleteThreadFailed: "فشل حذف المحادثة",
  saveEditsFailed: "فشل حفظ التعديلات",
  improveTextFailed: "فشل تحسين الصياغة",
  applyEditFailed: "فشل تطبيق التعديل",
  confirmActionFailed: "فشل التأكيد",
  cancelActionFailed: "فشل الإلغاء",
  uploadMediaFailed: "فشل رفع الملفات",
  noRewritableField: "لا يوجد حقل نصي مناسب لإعادة الصياغة.",
  searchSources: "مصادر البحث",
  resultsFound: "نتائج موجودة",
  cachedFrom: "مخزنة من",
  agentErrorFallback: "حدث خطأ غير متوقع في المحادثة. يمكنك المحاولة مرة أخرى أو إعادة تحميل الصفحة.",

  // Actions
  create: "إضافة",
  edit: "تعديل",
  delete: "حذف",
  save: "حفظ",
  cancel: "إلغاء",
  loadMore: "تحميل المزيد",
  add: "إضافة",
  back: "رجوع",
  search: "بحث",
  filter: "تصفية",
  export: "تصدير",
  import: "استيراد",
  refresh: "تحديث",
  view: "عرض",
  viewDetails: "عرض التفاصيل",
  close: "إغلاق",
  confirm: "تأكيد",
  submit: "إرسال",
  reset: "إعادة تعيين",
  clear: "مسح",
  selectAll: "تحديد الكل",
  deselectAll: "إلغاء تحديد الكل",

  // Auth
  adminSignIn: "تسجيل دخول المشرف",
  adminSignInDesc:
    "أدخل البريد الإلكتروني وكلمة المرور للوصول إلى لوحة التحكم.",
  email: "البريد الإلكتروني",
  password: "كلمة المرور",
  signIn: "تسجيل الدخول",
  signingIn: "جاري تسجيل الدخول...",
  signInFailed: "فشل تسجيل الدخول. تحقق من بياناتك.",
  signOut: "تسجيل الخروج",
  signUp: "إنشاء حساب",
  forgotPassword: "نسيت كلمة المرور؟",
  rememberMe: "تذكرني",

  // Entities
  developer: "مطور",
  addDeveloper: "إضافة مطور",
  bank: "بنك",
  loan: "قرض",
  addBank: "إضافة بنك",
  property: "عقار",
  addProperty: "إضافة عقار",
  order: "طلب",
  handoff: "تحويل",
  addOrder: "إضافة طلب",
  addKnowledgePage: "إضافة صفحة معرفة",
  addProduct: "إضافة منتج",
  addPhone: "إضافة رقم",
  user: "مستخدم",
  admin: "مشرف",
  team: "الفريق",
  teamDesc: "إدارة أعضاء الفريق الذين يمكنهم استخدام لوحة التحكم. يمكنك تعديل دور كل عضو فقط.",
  teamMembers: "أعضاء الفريق",
  noTeamMembers: "لا يوجد أعضاء في الفريق",
  teamEmptyDesc: "لم تتم إضافة أي أعضاء بعد. أضف مشرفين عبر صفحة المستخدمين.",
  legacyAdmin: "مشرف قديم",
  agentChat: "وكيل AI",
  myStats: "إحصائياتي",
  myThreads: "محادثاتي",
  myActivity: "نشاطي",

  // Fields
  name: "الاسم",
  slug: "المعرّف",
  status: "الحالة",
  priority: "الأولوية",
  contact: "جهة الاتصال",
  contactEmail: "البريد الإلكتروني للاتصال",
  phone: "الهاتف",
  website: "الموقع",
  description: "الوصف",
  address: "العنوان",
  price: "السعر",
  beds: "غرف نوم",
  baths: "حمامات",
  sqft: "المساحة (قدم²)",
  location: "الموقع",
  area: "المنطقة",
  type: "النوع",
  intent: "النية",
  notes: "ملاحظات",
  title: "العنوان",
  category: "التصنيف",
  role: "الدور",
  budget: "الميزانية",
  preferredLocation: "الموقع المفضل",
  source: "المصدر",
  read: "مقروء",
  unread: "غير مقروء",
  rating: "التقييم",
  comment: "تعليق",
  verifiedAt: "تاريخ التحقق",
  userId: "معرف المستخدم",
  total: "الإجمالي",
  loaded: "محمل",
  createdAt: "تاريخ الإنشاء",
  updatedAt: "تاريخ التحديث",
  actions: "الإجراءات",
  id: "المعرف",
  image: "الصورة",
  images: "الصور",
  logo: "الشعار",

  // Status values
  active: "نشط",
  pending: "قيد الانتظار",
  inactive: "غير نشط",
  suspended: "موقوف",
  low: "منخفض",
  medium: "متوسط",
  high: "عال",
  urgent: "عاجل",
  available: "متاح",
  sold: "تم البيع",
  reserved: "محجوز",
  property_financing: "تمويل عقاري",
  buy_property: "شراء عقار",
  sell_property: "بيع عقار",
  loan_consultation: "استشارة قرض",
  other: "أخرى",
  internal_db: "البيانات الداخلية",
  web_fallback: "مصادر خارجية",
  mixed: "مختلط",

  // Order statuses
  new_lead: "عميل محتمل جديد",
  contacted: "تم التواصل",
  qualified: "مؤهل",
  offer_made: "عرض مقدم",
  under_contract: "تحت العقد",
  closed_won: "تم الإغلاق (ربح)",
  closed_lost: "تم الإغلاق (خسارة)",

  all: "الكل",
  filterBy: "تصفية حسب",

  // Empty / messages
  noResults: "لا توجد نتائج",
  notFound: "غير موجود",
  deleteConfirm: "هل أنت متأكد من الحذف؟",
  userNotFound: "المستخدم غير موجود",
  developerNotFound: "المطور غير موجود",
  bankNotFound: "البنك غير موجود",
  propertyNotFound: "العقار غير موجود",
  orderNotFound: "الطلب غير موجود",
  noOrders: "لا توجد طلبات",
  noProperties: "لا توجد عقارات",
  noDevelopers: "لا يوجد مطورون",
  noBanks: "لا توجد بنوك",
  noKnowledgePages: "لا توجد صفحات معرفة",
  noNotifications: "لا توجد إشعارات",
  noReviews: "لا توجد تقييمات",
  noFavorites: "لا توجد مفضلات",
  noPrompts: "لا توجد نماذج",
  noVerifiedPhones: "لا توجد أرقام موثقة",
  noProducts: "لا توجد منتجات",
  noUsers: "لا يوجد مستخدمون",
  loading: "جاري التحميل...",
  error: "حدث خطأ",
  success: "تم بنجاح",
  warning: "تحذير",

  // Pages
  profile: "الملف الشخصي",
  activity: "النشاط",
  info: "المعلومات",
  relatedOrders: "الطلبات المرتبطة",
  products: "المنتجات",
  pipeline: "ال pipeline",
  overview: "نظرة عامة",
  pipelineOverview: "نظرة عامة على الـ pipeline",
  messagesByChannel: "الرسائل حسب القناة",
  topSearchedAreas: "أكثر المناطق بحثاً",
  updateStatus: "تحديث الحالة",
  knowledgePages: "صفحات المعرفة",
  verifiedPhones: "الأرقام الموثقة",
  authSystem: "النظام / المصادقة",
  settings: "الإعدادات",

  // Dashboard
  totalUsers: "إجمالي المستخدمين",
  active24h: "نشط (24 ساعة)",
  active30d: "نشط (30 يوم)",
  newUsers30d: "مستخدمون جدد (30 يوم)",
  totalProperties: "إجمالي العقارات",
  totalPartners: "إجمالي المطورين",
  totalBanks: "إجمالي البنوك",
  totalOrders: "إجمالي الطلبات",
  chartMessages: "الرسائل",
  chartNewUsers: "مستخدمون جدد",
  day: "يوم",
  week: "أسبوع",
  month: "شهر",
  year: "سنة",
  unnamed: "بدون اسم",
  salary: "الراتب",
  employment: "الوظيفة",
  firstTimeBuyer: "مشتري لأول مرة",
  kids: "الأطفال",
  minBeds: "أقل عدد غرف",
  noPromptsConfigured: "لا توجد نماذج مكوّنة",
  yes: "نعم",
  no: "لا",
  activityTimelinePlaceholder: "سيتم تعبئة خط الزمن عند تتبع أحداث المستخدم.",
  target: "الهدف",
  savedAt: "تاريخ الحفظ",
  recentActivity: "النشاط الأخير",
  quickStats: "إحصائيات سريعة",

  // Sales UI
  salesDashboardTitle: "لوحة المبيعات",
  salesDashboardDesc:
    "نظرة واضحة لمسار الطلبات ونقاط التحويل وإجراءات فريق المبيعات.",
  pipelineOrders: "مسار الطلبات",
  tableView: "عرض جدولي",
  salesNotificationsTitle: "إشعارات المبيعات",
  salesNotificationsDesc: "قائمة الإجراءات لمتابعة الطلبات والتحويلات البشرية.",
  actionQueue: "قائمة الإجراءات",
  noItems: "لا توجد عناصر.",
  acknowledged: "تم الاطلاع",
  resolve: "تمت المعالجة",
  acknowledge: "تأكيد الاطلاع",
  customerNeedsSummary: "ملخص احتياج العميل",
  handoffReason: "سبب التحويل",
  talkingPoints: "نقاط النقاش المقترحة",
  recommendationSummary: "ملخص التوصية",
  recommendationSource: "مصدر التوصية",
  nextAction: "الإجراء التالي",
  assignedTo: "مسند إلى",
  salesBriefing: "ملخص جاهزية المبيعات",
  salesWorkbench: "منصة متابعة المبيعات",
  moveToNextStage: "نقل إلى المرحلة التالية",
  terminalStage: "هذا الطلب في مرحلة نهائية.",
  orderDetails: "تفاصيل الطلب",
  customer: "العميل",
  timelineSla: "الزمن و SLA",
  created: "تاريخ الإنشاء",
  ageHours: "العمر (ساعة)",
  confidence: "مستوى الثقة",
  relatedEntities: "الكيانات المرتبطة",
  bankProduct: "منتج البنك",
  unnamedCustomer: "عميل بدون اسم",
  noPreferredArea: "لا يوجد موقع مفضل",
  sourceHintProfile: "المصدر: userProfiles",
  sourceHintOrderSummary: "المصدر: حقول order/agent",
  sourceHintNotifications: "المصدر: notifications.metadata",
  sourceHintConversation: "المصدر: threads/messages",
  sourceHintOrders: "المصدر: orders",
  conversation: "المحادثة",
  userAgentConversation: "محادثة العميل مع الوكيل",
  noConversation: "لا توجد محادثة لهذا المستخدم.",
  noMessages: "لا توجد رسائل بعد.",
  customerLabel: "العميل",
  agentLabel: "الوكيل",
  roleUpdated: "تم تحديث الدور",
  roleUpdateFailed: "فشل تحديث الدور",
  missingPhoneForRole: "لا يوجد رقم هاتف لهذا المستخدم لتغيير الدور.",
  switchRole: "تبديل الدور",
  preferredArea: "المنطقة المفضلة",
  maxBudget: "الميزانية القصوى",
  searchCustomersOrders:
    "ابحث بالعميل أو الهاتف أو النية أو البنك أو العقار...",
  searchBanks: "ابحث باسم البنك أو المعرّف أو البريد...",
  searchProperties: "ابحث بالعنوان أو الموقع أو المنطقة...",
  addBankLabel: "إضافة بنك",
  addPropertyLabel: "إضافة عقار",
  manageBanksDesc: "إدارة البنوك ومنتجاتها بصيغة واضحة لفريق المبيعات.",
  managePropertiesDesc: "إدارة المخزون العقاري وجودة القوائم.",
  manageBankProductsDesc:
    "إدارة منتجات التمويل والقروض بطريقة واضحة لفريق المبيعات.",
  createProduct: "إضافة منتج",
  productsList: "قائمة المنتجات",
  selectBank: "اختر بنكاً",
  productName: "اسم المنتج",
  productType: "نوع المنتج",
  createProductAction: "إضافة المنتج",
  creating: "جاري الإنشاء...",
  editNamePrompt: "الاسم الجديد للمنتج",
  deleteBankConfirm: "هل أنت متأكد من حذف البنك؟",
  deleteProductConfirm: "هل أنت متأكد من حذف المنتج؟",
  bankDeleted: "تم حذف البنك",
  bankDeleteFailed: "فشل حذف البنك",
  productDeleted: "تم حذف المنتج",
  productDeleteFailed: "فشل حذف المنتج",
  productUpdated: "تم تحديث المنتج",
  productUpdateFailed: "فشل تحديث المنتج",
  productCreated: "تم إنشاء المنتج",
  productCreateFailed: "فشل إنشاء المنتج",
  noOrdersFound: "لا توجد طلبات مطابقة.",
  noBanksFound: "لا توجد بنوك مطابقة.",
  noPropertiesFound: "لا توجد عقارات مطابقة.",
  totalOrdersLabel: "إجمالي الطلبات",
  conversionRate: "نسبة التحويل",
  unassigned: "غير مسند",
  staleLeads: "عملاء قدامى بدون إغلاق",
  customersCount: "العملاء",
  active24hLabel: "نشط خلال 24 ساعة",
  ordersTrend: "اتجاه الطلبات",
  messagesTrend: "اتجاه الرسائل",
  newCustomersTrend: "اتجاه العملاء الجدد",
  pipelineStages: "مراحل المسار",
  recentSalesActivity: "آخر نشاط مبيعات",
  noRecentActivity: "لا يوجد نشاط حديث.",
  viewOrder: "عرض الطلب",
  openConversation: "فتح المحادثة",
  reasonsTimeline: "تسلسل الأسباب",
  discussedTopics: "المواضيع التي تمت مناقشتها",
  noDiscussedTopics: "لا توجد مواضيع مسجلة.",
  customerInterest: "مستوى الاهتمام",
  interestLevel: "مستوى الاهتمام",
  highInterest: "اهتمام عالٍ",
  mediumInterest: "اهتمام متوسط",
  lowInterest: "اهتمام منخفض",
  unknownInterest: "غير معروف",
  knowledgeBase: "قاعدة المعرفة والبحث",
  searchQueries: "استعلامات البحث",
  linksSearched: "الروابط التي تم البحث فيها",
  noSearchHistory: "لا يوجد سجل بحث.",
  noLinksSearched: "لم يتم البحث في أي روابط.",
  lastActivity: "آخر نشاط",
  lastAction: "آخر إجراء",
  noActivity: "لا نشاط",
  actionMessageSent: "رسالة",
  actionSearch: "بحث",
  actionOrderCreated: "طلب جديد",
  actionLogin: "تسجيل دخول",
  actionPropertyViewed: "عرض عقار",
  basicInfo: "المعلومات الأساسية",
  clientProfile: "ملف العميل",
  financialInfo: "المعلومات المالية",
  preferences: "التفضيلات",
  adminSettings: "إعدادات المشرف",
  editUser: "تعديل بيانات العميل",
  editUserDesc: "قم بتعديل معلومات العميل الأساسية والتفضيلات.",
  saveChanges: "حفظ التغييرات",
  userUpdated: "تم تحديث بيانات العميل",
  userUpdateFailed: "فشل تحديث بيانات العميل",
  showDetails: "عرض التفاصيل",
  hideDetails: "إخفاء التفاصيل",
  searchAndConversations: "البحث والمحادثات",
  noHandoffs: "لا توجد تحويلات",
  free: "مجاني",
  paid: "مدفوع",
  verified: "موثق",
  planType: "نوع الخطة",
  handoffs: "التحويلات",
  generateSummary: "إنشاء ملخص",
  generateSummaryDesc: "إنشاء ملخص سريع لحالة العميل",
  summaryLoading: "جاري إنشاء الملخص...",
  quickSummary: "ملخص سريع",
  recentSearches: "عمليات البحث الأخيرة",
  conversationContext: "سياق المحادثة",
  lastConversation: "آخر محادثة",
  noSearches: "لا توجد عمليات بحث",
  staleLeadsAlert: "عملاء قدامى يحتاجون متابعة",
  unassignedAlert: "طلبات غير مسنده للفريق",
  aiCosts: "تكلفة AI",
  toolCosts: "تكلفة الأدوات",
  planExpiresAt: "تاريخ انتهاء الخطة",
  chatLimit: "حد المحادثات",

  // Charts
  messagesPerDay: "الرسائل يومياً",
  ordersPerDay: "الطلبات يومياً",
  searchesPerDay: "البحث يومياً",
  pipelineDistribution: "توزيع المسار",
  channelDistribution: "توزيع القنوات",
  activityOverTime: "النشاط عبر الزمن",
  last7Days: "آخر ٧ أيام",
  last30Days: "آخر ٣٠ يوم",

  // Dashboard sections
  agentPerformance: "أداء الوكيل",
  platformOverview: "نظرة عامة على المنصة",
  totalSearches: "إجمالي البحث",
  active24hours: "نشط ٢٤ ساعة",
  newUsersCount: "مستخدمون جدد",
  totalMessagesCount: "إجمالي الرسائل",
  conversationsCount: "محادثات",
  verifiedPhonesCount: "أرقام موثقة",
  activeSessions: "جلسات نشطة",

  // Property details
  propertyInfo: "معلومات العقار",
  propertySpecs: "المواصفات",
  bedrooms: "غرف نوم",
  bathrooms: "حمامات",
  propertyOrders: "الطلبات المرتبطة",
  viewsCount: "المشاهدات",

  // User details
  userActivityChart: "رسم النشاط",
  knowledgeResearch: "البحث المعرفي",
  customerNeeds: "احتياجات العميل",

  // Misc
  dragToReorder: "اسحب لإعادة الترتيب",
  clickToExpand: "انقر للتوسيع",
  clickToCollapse: "انقر للطي",
  noDataAvailable: "لا توجد بيانات",
  llmAnalytics: "تحليلات AI",
  tokenUsage: "استخدام الرموز",
  costPerUser: "التكلفة لكل مستخدم",
  successRate: "معدل النجاح",
  modelPricing: "أسعار النماذج",
  businessMetrics: "مقاييس الأعمال",
  conversionFunnel: "قمع التحويل",
  primary: "رئيسية",
  dragImagesHere: "اسحب الصور هنا أو انقر للاختيار",
  maxImages: "الحد الأقصى",
  imagesUploaded: "صور مرفوعة",
  eligibilityRules: "شروط الأهلية",
  loanDetails: "تفاصيل القرض",
  requiredDocuments: "المستندات المطلوبة",
  additionalNotes: "ملاحظات إضافية",
  minSalary: "الحد الأدنى للراتب",
  employmentType: "نوع الوظيفة",
  minEmploymentYears: "الحد الأدنى لسنوات الخبرة",
  minAge: "الحد الأدنى للعمر",
  maxAge: "الحد الأقصى للعمر",
  maxDebtRatio: "الحد الأقصى لنسبة الدين",
  minCreditScore: "الحد الأدنى للتصنيف الائتماني",
  minDownPayment: "الحد الأدنى للدفعة الأولى",
  minLoanAmount: "الحد الأدنى لمبلغ القرض",
  maxLoanAmount: "الحد الأقصى لمبلغ القرض",
  loanTerm: "مدة القرض",
  interestRate: "سعر الفائدة",
  processingFee: "رسوم المعالجة",
  earlyPaymentFee: "رسوم السداد المبكر",
  latePaymentFee: "رسوم التأخير",
  addDocument: "أضف مستند",
  suggestions: "اقتراحات",
  anyType: "أي نوع",
  employed: "موظف",
  selfEmployed: "عمل حر",
  retired: "متقاعد",
  firstTimeBuyerOnly: "مشتري لأول مرة فقط",
  notFirstTimeBuyerOnly: "مشتري سابق فقط",

  // Settings
  analyticsFullPage: "صفحة التحليلات الكاملة",
  forMoreDetails: "للمزيد من التفاصيل",
  modeLabel: "الوضع",
  modelLabel: "النموذج",
  promptsSettings: "إعدادات النماذج",
  enableCache: "تفعيل التخزين المؤقت",
  streamingResponse: "الاستجابة التدريجية",
  enableWebSearch: "تفعيل البحث على الإنترنت",
  autoHandoff: "التحويل التلقائي للبشر",
  rememberContext: "تذكر السياق",
  totalTokens: "إجمالي الرموز",
  inputTokens: "رمز الإدخال",
  outputTokens: "رمز الإخراج",
  costEstimate: "تقدير التكلفة",
  modelUsage: "استخدام النماذج",
  costPerRequest: "التكلفة لكل طلب",
  emailPlaceholder: "مثال: admin@example.com",

  // Property edit / Dashboard
  propertyUpdated: "تم تحديث العقار",
  propertyUpdateFailed: "فشل تحديث العقار",
  showingCountOfTotal: "عرض {count} من {total} عقار",
  manageDevelopersDesc: "إدارة المطورين والشركاء العقاريين",
  withProperties: "لديهم عقارات",
  conversionRateLabel: "معدل التحويل",
  customersLabel: "العملاء",
  staleOrders: "طلبات قديمة",
  weeklyTokens: "رمز الأسبوع",
  weeklyRequests: "طلب الأسبوع",
  editBank: "تعديل البنك",
  bankProducts: "منتجات البنوك",
  bankUpdated: "تم تحديث البنك",
  bankUpdateFailed: "فشل تحديث البنك",
  nameAndSlugRequired: "الاسم والمعرّف مطلوبان",
  saving: "جاري الحفظ...",
  contactEmailLabel: "البريد الإلكتروني للاتصال",

  // Agent / ActionCard
  editableDetails: "التفاصيل القابلة للتعديل",
  saveEdits: "حفظ التعديلات",
  uploadModule: "رفع (صور/شعار)",
  uploading: "جاري الرفع...",
  uploadFiles: "رفع ملفات",
  actionExecuted: "تم تنفيذ هذا الإجراء.",
  executionFailed: "فشل التنفيذ.",
  actionClosed: "هذا الإجراء مغلق.",
  payloadInvalid: "JSON غير صالح. أصلحه قبل الحفظ.",
  failedToUpdatePayload: "فشل تحديث البيانات",
  failedToConfirmAction: "فشل تأكيد الإجراء",
  failedToCancelAction: "فشل إلغاء الإجراء",
  failedToUploadMedia: "فشل رفع الوسائط",
  executionFailedDesc: "فشل التنفيذ. يمكنك فحص النتيجة في هذه البطاقة.",
  orderN: "الترتيب {n}",
  loadingSessions: "جاري تحميل الجلسات...",
  conversations: "المحادثات",
  today: "اليوم",
  thisWeek: "هذا الأسبوع",
  older: "أقدم",
  newChat: "محادثة جديدة",
  editTitle: "تعديل العنوان",
  deleteConversation: "حذف المحادثة",
  searchSessions: "ابحث في الجلسات...",
  noMatchingSessions: "لا توجد جلسات مطابقة.",
  noSessionsYet: "لا توجد جلسات بعد.",
  chatHistory: "سجل المحادثات",
  needsFollowUp: "تحتاج متابعة",
  excellent: "ممتاز",
  good: "جيد",
  needsImprovement: "يحتاج تحسين",
  weeklyTokensAndOrders: "رمز الأسبوع والطلبات",
  aiUsageTitle: "استخدام الذكاء الاصطناعي",
  details: "تفاصيل",
  totalDevelopers: "إجمالي المطورين",
  searchDevelopersPlaceholder: "ابحث باسم المطور أو المعرف...",
  propertyCount: "{n} عقار",
  handoffsPending: "تحويلات معلقة",
  tryChangingSearch: "جرب تغيير معايير البحث",
  showingCountOfTotalUsers: "عرض {count} من {total} مستخدم",
  showingCountOfTotalOrders: "عرض {count} من {total} طلب",
  showingCountOfTotalPrompts: "عرض {count} من {total} قالب",
  noPromptsCurrently: "لا توجد قوالب نصية حالياً",
} as const;

export type ArKey = keyof typeof ar;
