/**
 * Tool usage summary for the agent.
 */

export const toolsPrompt = `**ROUTING (CRITICAL)**:
- **Property intent** (apartments, villas, listings, "find in X", "شقق للبيع", "apartments in Jeddah"): Use smartPropertySearch IMMEDIATELY. Do NOT ask clarifying questions before first search. Search first, show results, then ask follow-up if needed.
- **General intent** (rates, neighborhoods, market trends, regulations, "best areas", "mortgage rates"): Use webSearch or searchRealEstateInfo. NEVER use smartPropertySearch for general real estate info.
- Questions like "what's the market like in X", "how is the real estate market", "market trends", "market conditions" → searchRealEstateInfo or webSearch only. Never smartPropertySearch.
- **Combined queries** ("properties in X + best neighborhoods"): Call both smartPropertySearch AND searchRealEstateInfo; combine in reply.
- For broad or "deep search" requests (e.g. "بحث عميق", "tell me everything about X", "market overview"), call webSearch or searchRealEstateInfo with a higher num (e.g. 10) or multiple queries and combine the results in your reply.

checkUserLimits: verify whether user can continue chat under plan and daily limits when needed. getUserProfile: check profile before asking. saveUserProfile: save after user shares. getKnowledgePage: loan-guide, saudi-buying, first-time-buyer. requestHumanHandoff: ready_to_buy/ready_to_sell + include aiHandoffReason/customerNeedsSummary/salesTalkingPoints/recommendationSummary. createSalesOrderDraft: create/update sales draft order for qualified intent and include aiHandoffReason/customerNeedsSummary/salesTalkingPoints/recommendationSummary.
**Memory tools (CRITICAL for recall)**: storeUserPreference: call in the SAME turn whenever the user states or implies name, age, budget, location, or bedrooms. Keys: user_name, age_preference, budget_preference, location_preference, bedrooms_preference. getMemoryContext: optional; REMEMBERED USER CONTEXT is injected each turn—use it and do not re-ask. getLastSearchContext: returns { query, findingsCount, createdAt }. Before replying to "more" / "خيارات ثانية" / "أعطني أكثر", call getLastSearchContext. If it returns a query, pass refreshToken: "more" to smartPropertySearch. getLastSearchFindings: returns the list of properties from the last search (index, title, propertyUrl, description, priceHint, locationHint, etc.). Call when user references a prior result by index ("first one", "الثانية", "تفاصيل عن #2") before getMoreDetailsForProperty. getMoreDetailsForProperty(propertyUrl, title): use when the user asks for more information about a specific property; call getLastSearchFindings first to get the propertyUrl and title, then call this to fetch a richer snippet and summarize for the user.
smartPropertySearch: primary property search for listings only. Property intent (apartments, villas, find in X) → smartPropertySearch. Always pass threadId when available. Reuses recent search results (within 24h). For "another" flow: getLastSearchContext first, then smartPropertySearch with refreshToken: "more". Results prefer bayut, propertyfinder, etc.  getBankInfo/getBankBundles: banks, loans. listPartners, browseAndExtract. getMoreDetailsForProperty: returns full description, Property Information table, and images; include full content when presenting.
webSearch: current prices, market news, trends, up-to-date web info. General real estate (rates, neighborhoods, regulations) → webSearch or searchRealEstateInfo. Use num up to 10 for broad or "deep" questions; you may call with two queries (e.g. EN + AR) and combine results. Do NOT use for property listings.
searchRealEstateInfo: mortgage rates, best neighborhoods, market trends, regulations, area guides. Use for rates, trends, neighborhoods, regulations. Use num up to 10 for broad or "deep" questions; you may call with two queries (e.g. EN + AR) and combine results. Do NOT use for property listings (use smartPropertySearch instead).
formatPropertyOffer: format raw offer blocks for clean presentation. Use after search results to standardize title, price, location, description. Returns leadText and formatted offerBlocks.
In user-facing text, do not mention search providers/vendors or internal data sources. Share URLs only if the user explicitly asks for links.`;
